CREATE SEQUENCE board_seq
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE;
​
CREATE TABLE BOARD_TBL (
	BOARD_NUM NUMBER DEFAULT 0,
	BOARD_WRITER VARCHAR2(30) NOT NULL,
	BOARD_PASS VARCHAR2(20) NOT NULL,
	BOARD_SUBJECT VARCHAR2(100 CHAR) NOT NULL,
	BOARD_CONTENT CLOB NOT NULL,
	BOARD_ORIGINAL_FILE NVARCHAR2(200),
	BOARD_FILE NVARCHAR2(200),
	BOARD_RE_REF NUMBER NOT NULL,
	BOARD_RE_LEV NUMBER NOT NULL,
	BOARD_RE_SEQ NUMBER NOT NULL,
	BOARD_READCOUNT NUMBER DEFAULT 0,
	BOARD_DATE DATE,
	PRIMARY KEY(BOARD_NUM)
);

COMMENT ON COLUMN BOARD_TBL.BOARD_NUM IS '게시글 번호';
COMMENT ON COLUMN BOARD_TBL.BOARD_WRITER IS '게시글 작성자';
COMMENT ON COLUMN BOARD_TBL.BOARD_PASS IS '게시글 비밀번호';
COMMENT ON COLUMN BOARD_TBL.BOARD_SUBJECT IS '게시글 제목';
COMMENT ON COLUMN BOARD_TBL.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD_TBL.BOARD_ORIGINAL_FILE IS '게시글 첨부 파일(원본)';
COMMENT ON COLUMN BOARD_TBL.BOARD_FILE IS '게시글 첨부 파일(암호화)';
COMMENT ON COLUMN BOARD_TBL.BOARD_RE_REF IS '게시글 답글의 원 게시글(관련글) 번호';
COMMENT ON COLUMN BOARD_TBL.BOARD_RE_LEV IS '게시글 답글 레벨';
COMMENT ON COLUMN BOARD_TBL.BOARD_RE_SEQ IS '게시글 답글 순서';
COMMENT ON COLUMN BOARD_TBL.BOARD_READCOUNT IS '게시글 조회수';
COMMENT ON COLUMN BOARD_TBL.BOARD_DATE IS '게시글 작성일자';
​