CREATE TABLE MY_SCRAP (
SCRAPNO NUMBER NOT NULL,
ID VARCHAR2(50) NOT NULL,
BOARD_NUMBER NUMBER NOT NULL,
SCRAPDATE DATE DEFAULT SYSDATE,
CONSTRAINT SCRAP_PK PRIMARY KEY (SCRAPNO),
CONSTRAINT SCRAP_FK FOREIGN KEY (ID)
REFERENCES MEMBER_TBL(ID) ON DELETE CASCADE
);

DROP TABLE MY_SCRAP;