-- 근거 자료 :
-- https://www.fatsecret.kr/%EC%B9%BC%EB%A1%9C%EB%A6%AC-%EC%98%81%EC%96%91%EC%86%8C/search

CREATE TABLE CU_NUTRI_INFO_TBL (
	NUM	NUMBER(10) PRIMARY KEY,
	FOOD_ID NUMBER(19) NOT NULL,
	FOOD_NAME NVARCHAR2(255) NOT NULL,
	MAKER_NAME	NVARCHAR2(50),
	NUTR_CONT1	NUMBER(10,2),
	NUTR_CONT2	NUMBER(10,2),
	NUTR_CONT3	NUMBER(10,2),
	NUTR_CONT4	NUMBER(10,2),
	NUTR_CONT5	NUMBER(10,2),
	NUTR_CONT6	NUMBER(10,2),
	NUTR_CONT7	NUMBER(10,2),
	NUTR_CONT8	NUMBER(10,2),
	NUTR_CONT9	NUMBER(10,2)
);

COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUM IS '번호(기본키)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.FOOD_ID IS '식품 테이블(CU_TBL)의 식품번호';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.FOOD_NAME IS '식품명';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.MAKER_NAME IS '제조사명';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT1 IS '열량(KCAL)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT2 IS '탄수화물(G)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT3 IS '단백질(G)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT4 IS '지방(G)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT5 IS '당류(G)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT6 IS '나트륨(MG)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT7 IS '콜레스테롤(MG)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT8 IS '포화지방산(G)(1회제공량당)';
COMMENT ON COLUMN CU_NUTRI_INFO_TBL.NUTR_CONT9 IS '트랜스지방(G)(1회제공량당)';

CREATE SEQUENCE CU_NUTRI_INFO_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE;