CREATE TABLE NUTRI_STD_TBL (
	NUM NUMBER(2) PRIMARY KEY,
	GENDER NCHAR(1) NOT NULL,
	AGE NVARCHAR2(10) NOT NULL,
	ENERGY NUMBER(4) DEFAULT 0,
	CARBOHYDRATE NUMBER(3) DEFAULT 0,
	PROTEIN NUMBER(2) DEFAULT 0,
	SUGAR NVARCHAR2(10),
	NATRIUM NUMBER(4) DEFAULT 0,
	CHOLESTEROL NUMBER(3),
	FAT NVARCHAR2(10),
	FATTY_ACID NUMBER(2),
	TRANS_FATTY_ACID NUMBER(2)
);

COMMENT ON COLUMN NUTRI_STD_TBL.NUM IS '기본키';
COMMENT ON COLUMN NUTRI_STD_TBL.GENDER IS '성별';
COMMENT ON COLUMN NUTRI_STD_TBL.AGE IS '연령';
COMMENT ON COLUMN NUTRI_STD_TBL.ENERGY IS '에너지(KCAL/일)';
COMMENT ON COLUMN NUTRI_STD_TBL.CARBOHYDRATE IS '탄수화물(G/일)';
COMMENT ON COLUMN NUTRI_STD_TBL.PROTEIN IS '단백질(G/일)';
COMMENT ON COLUMN NUTRI_STD_TBL.SUGAR IS '당류(%) : 총에너지 대비';
COMMENT ON COLUMN NUTRI_STD_TBL.NATRIUM IS '나트륨(MG)';
COMMENT ON COLUMN NUTRI_STD_TBL.CHOLESTEROL IS '콜레스테롤(MG) : 지질(총계)';
COMMENT ON COLUMN NUTRI_STD_TBL.FAT IS '지방(%) : 지질';
COMMENT ON COLUMN NUTRI_STD_TBL.FATTY_ACID IS '포화지방산(%) : 지질';
COMMENT ON COLUMN NUTRI_STD_TBL.TRANS_FATTY_ACID IS '트랜스지방산(%) : 지질';


CREATE SEQUENCE NUTRI_STD_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE;
