-- 근거 자료 :
-- 식품영양성분DB(NEW) : 공공데이터 "식품안전나라"
-- : https://www.foodsafetykorea.go.kr/api/newDatasetDetail.do
CREATE TABLE NUTRI_TBL (
	NUM	NUMBER(10) primary key,
	FOOD_ID NUMBER(19) not null,
	FOOD_NAME NVARCHAR2(255) not null,
	FOOD_SEARCH_NAME NVARCHAR2(255),
	FOOD_CD	 NVARCHAR2(10),
	SAMPLING_REGION_NAME  NVARCHAR2(10),
	SAMPLING_MONTH_NAME	 NVARCHAR2(10),
	SAMPLING_REGION_CD  NVARCHAR2(2),
	SAMPLING_MONTH_CD NVARCHAR2(5),
	GROUP_NAME  NVARCHAR2(20),
	DESC_KOR  NVARCHAR2(255),
	RESEARCH_YEAR  NVARCHAR2(4),
	MAKER_NAME	 NVARCHAR2(20),
	SUB_REF_NAME  NVARCHAR2(100),
	SERVING_SIZE  NUMBER(10,2),
	SERVING_UNIT  NVARCHAR2(10),
	NUTR_CONT1	NUMBER(10,2),
	NUTR_CONT2	NUMBER(10,2),
	NUTR_CONT3	NUMBER(10,2),
	NUTR_CONT4	NUMBER(10,2),
	NUTR_CONT5	NUMBER(10,2),
	NUTR_CONT6	NUMBER(10,2),
	NUTR_CONT7	NUMBER(10,2),
	NUTR_CONT8	NUMBER(10,2),
	NUTR_CONT9	NUMBER(10,2)
);

COMMENT ON COLUMN NUTRI_TBL.NUM IS '번호(기본키)';
COMMENT ON COLUMN NUTRI_TBL.FOOD_ID IS '식품 테이블의 식품번호';
COMMENT ON COLUMN NUTRI_TBL.FOOD_NAME IS '식품 테이블의 식품명';
COMMENT ON COLUMN NUTRI_TBL.FOOD_SEARCH_NAME IS '식품 테이블의 검색시 사용한 식품명';
COMMENT ON COLUMN NUTRI_TBL.FOOD_CD IS '식품코드';
COMMENT ON COLUMN NUTRI_TBL.SAMPLING_REGION_NAME IS '지역명';
COMMENT ON COLUMN NUTRI_TBL.SAMPLING_MONTH_NAME IS '채취월';
COMMENT ON COLUMN NUTRI_TBL.SAMPLING_REGION_CD IS '지역코드';
COMMENT ON COLUMN NUTRI_TBL.SAMPLING_MONTH_CD IS '채취월코드';
COMMENT ON COLUMN NUTRI_TBL.GROUP_NAME IS '식품군';
COMMENT ON COLUMN NUTRI_TBL.DESC_KOR IS '식품이름';
COMMENT ON COLUMN NUTRI_TBL.RESEARCH_YEAR IS '조사년도';
COMMENT ON COLUMN NUTRI_TBL.MAKER_NAME IS '제조사명';
COMMENT ON COLUMN NUTRI_TBL.SUB_REF_NAME IS '자료출처';
COMMENT ON COLUMN NUTRI_TBL.SERVING_SIZE IS '총내용량';
COMMENT ON COLUMN NUTRI_TBL.SERVING_UNIT IS '총내용량단위';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT1 IS '열량(KCAL)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT2 IS '탄수화물(G)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT3 IS '단백질(G)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT4 IS '지방(G)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT5 IS '당류(G)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT6 IS '나트륨(MG)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT7 IS '콜레스테롤(MG)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT8 IS '포화지방산(G)(1회제공량당)';
COMMENT ON COLUMN NUTRI_TBL.NUTR_CONT9 IS '트랜스지방(G)(1회제공량당)';

CREATE SEQUENCE NUTRI_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE;