CREATE TABLE SHOPPING_HISTORY_TBL (
	ID NUMBER(10) PRIMARY KEY,
	USER_ID VARCHAR2(20),
	FOOD_NAME NVARCHAR2(255),
	QUANTITY NUMBER(10) DEFAULT 0,
	PURCHASE_DATE DATE
);

COMMENT ON COLUMN SHOPPING_HISTORY_TBL.ID IS '기본키';
COMMENT ON COLUMN SHOPPING_HISTORY_TBL.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN SHOPPING_HISTORY_TBL.FOOD_NAME IS '구매한 식품명';
COMMENT ON COLUMN SHOPPING_HISTORY_TBL.QUANTITY IS '구매수량';
COMMENT ON COLUMN SHOPPING_HISTORY_TBL.PURCHASE_DATE IS '구매일';

CREATE SEQUENCE SHOPPING_HISTORY_SEQ
MINVALUE 1
MAXVALUE 9999999999
INCREMENT BY 1
START WITH 1
NOCYCLE;