CREATE TABLE USER_ROLES (
    USER_ROLE_ID    NUMBER(11)  NOT NULL,
    USERNAME        VARCHAR(20) NOT NULL,
    ROLE            VARCHAR(45) NOT NULL,
    PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME)
    REFERENCES DEMO_TBL (ID)
);

CREATE SEQUENCE USER_ROLES_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    NOCYCLE;