CREATE TABLE DEMO_TBL (
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(60) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
GENDER CHAR NOT NULL,
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
PHONE VARCHAR2(13) NOT NULL UNIQUE,
ZIP CHAR(5),
ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
ENABLED NUMBER(1) DEFAULT 0
);

COMMENT ON COLUMN DEMO_TBL.ID IS '아이디';
COMMENT ON COLUMN DEMO_TBL.PW IS '패스워드';
COMMENT ON COLUMN DEMO_TBL.NAME IS '이름';
COMMENT ON COLUMN DEMO_TBL.GENDER IS '성별';
COMMENT ON COLUMN DEMO_TBL.EMAIL IS '이메일';
COMMENT ON COLUMN DEMO_TBL.PHONE IS '휴대전화';
COMMENT ON COLUMN DEMO_TBL.ZIP IS '우편번호';
COMMENT ON COLUMN DEMO_TBL.ADDRESS IS '도로명 주소';
COMMENT ON COLUMN DEMO_TBL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN DEMO_TBL.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN DEMO_TBL.JOINDATE IS '가입일';
COMMENT ON COLUMN DEMO_TBL.ENABLED IS '회원정보 사용 여부';