CREATE TABLE INFINITE_FOOD_TBL (
	FOOD_NUM NUMBER(10) PRIMARY KEY,
	FOOD_SITE NVARCHAR2(300)
);

CREATE SEQUENCE INFINITE_FOOD_SEQ 
MINVALUE 1 
MAXVALUE 9999999999 
INCREMENT BY 1
START WITH 1
NOCYCLE;
