CREATE TABLE MEMBER_TBL (
ID VARCHAR2(20) PRIMARY KEY,
PW VARCHAR2(60) NOT NULL, -- 패쓰워드 암호화 위한 변경 : PW VARCHAR2(60) NOT NULL, 
NAME VARCHAR2(100) NOT NULL,
GENDER CHAR NOT NULL,
EMAIL VARCHAR2(50) NOT NULL UNIQUE,
MOBILE VARCHAR2(13) NOT NULL UNIQUE,
PHONE VARCHAR2(13) NOT NULL,
ZIP CHAR(5),
ROAD_ADDRESS NVARCHAR2(100),
JIBUN_ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
ENABLED NUMBER(1) DEFAULT 0;
);

-- 패쓰워드 필드 자료형(자릿수) 변경
ALTER TABLE MEMBER_TBL MODIFY PW VARCHAR2(60);

-- ENABLED 필드 추가
ALTER TABLE MEMBER_TBL ADD ENABLED NUMBER(1) DEFAULT 0;
COMMENT ON COLUMN MEMBER_TBL.ENABLED IS '회원정보 사용 여부';

-- 기존 데이터에 대한 ENABLED 필드의 사용가 변경(1) 
UPDATE MEMBER_TBL SET ENABLED = 1;


COMMENT ON COLUMN MEMBER_TBL.ID IS '아이디';
COMMENT ON COLUMN MEMBER_TBL.PW IS '패쓰워드';
COMMENT ON COLUMN MEMBER_TBL.NAME IS '이름';
COMMENT ON COLUMN MEMBER_TBL.GENDER IS '성별';
COMMENT ON COLUMN MEMBER_TBL.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER_TBL.MOBILE IS '연락처1(휴대폰)';
COMMENT ON COLUMN MEMBER_TBL.PHONE IS '연락처2(일반전화)';
COMMENT ON COLUMN MEMBER_TBL.ZIP IS '우편번호';
COMMENT ON COLUMN MEMBER_TBL.ROAD_ADDRESS IS '도로명 주소';
COMMENT ON COLUMN MEMBER_TBL.JIBUN_ADDRESS IS '지번 주소';
COMMENT ON COLUMN MEMBER_TBL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN MEMBER_TBL.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER_TBL.JOINDATE IS '가입일';
COMMENT ON COLUMN MEMBER_TBL.ENABLED IS '회원정보 사용 여부';
 
DROP TABLE MEMBER_TBL;

----------------------------------------------------------

CREATE TABLE MEMBER_TBL (
ID VARCHAR2(20) CONSTRAINT MEMBER_TBL_ID_PK PRIMARY KEY,
PW VARCHAR2(60) CONSTRAINT MEMBER_TBL_PW_NN NOT NULL,
NAME VARCHAR2(100) CONSTRAINT MEMBER_TBL_NAME_NN NOT NULL,
GENDER CHAR CONSTRAINT MEMBER_TBL_GENDER_NN NOT NULL,
EMAIL VARCHAR2(50) CONSTRAINT MEMBER_TBL_EMAIL_NN NOT NULL,
MOBILE VARCHAR2(13) CONSTRAINT MEMBER_TBL_MOBILE_NN NOT NULL,
PHONE VARCHAR2(13) CONSTRAINT MEMBER_TBL_PHONE_NN NOT NULL,
ZIP CHAR(5),
ROAD_ADDRESS NVARCHAR2(100),
JIBUN_ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
ENABLED NUMBER(1) DEFAULT 0
CONSTRAINT MEMBER_TBL_EMAIL_U UNIQUE(EMAIL),
CONSTRAINT MEMBER_TBL_MOBILE_U UNIQUE(MOBILE)
);


COMMENT ON COLUMN MEMBER_TBL.ID IS '아이디';
COMMENT ON COLUMN MEMBER_TBL.PW IS '패쓰워드';
COMMENT ON COLUMN MEMBER_TBL.NAME IS '이름';
COMMENT ON COLUMN MEMBER_TBL.GENDER IS '성별';
COMMENT ON COLUMN MEMBER_TBL.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER_TBL.MOBILE IS '연락처1(휴대폰)';
COMMENT ON COLUMN MEMBER_TBL.PHONE IS '연락처2(일반전화)';
COMMENT ON COLUMN MEMBER_TBL.ZIP IS '우편번호';
COMMENT ON COLUMN MEMBER_TBL.ROAD_ADDRESS IS '도로명 주소';
COMMENT ON COLUMN MEMBER_TBL.JIBUN_ADDRESS IS '지번 주소';
COMMENT ON COLUMN MEMBER_TBL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN MEMBER_TBL.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER_TBL.JOINDATE IS '가입일';
COMMENT ON COLUMN MEMBER_TBL.ENABLED IS '회원정보 사용 여부';
 
DROP TABLE MEMBER_TBL;

------------------------------------------------------------------

CREATE TABLE MEMBER_TBL (
ID VARCHAR2(20),
PW VARCHAR2(60) CONSTRAINT MEMBER_TBL_PW_NN NOT NULL,
NAME VARCHAR2(100) CONSTRAINT MEMBER_TBL_NAME_NN NOT NULL,
GENDER CHAR CONSTRAINT MEMBER_TBL_GENDER_NN NOT NULL,
EMAIL VARCHAR2(50) CONSTRAINT MEMBER_TBL_EMAIL_NN NOT NULL,
MOBILE VARCHAR2(13) CONSTRAINT MEMBER_TBL_MOBILE_NN NOT NULL,
PHONE VARCHAR2(13) CONSTRAINT MEMBER_TBL_PHONE_NN NOT NULL,
ZIP CHAR(5),
ROAD_ADDRESS NVARCHAR2(100),
JIBUN_ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
ENABLED NUMBER(1) DEFAULT 0
CONSTRAINT MEMBER_TBL_ID_PK PRIMARY KEY(ID),
CONSTRAINT MEMBER_TBL_EMAIL_U UNIQUE(EMAIL),
CONSTRAINT MEMBER_TBL_MOBILE_U UNIQUE(MOBILE)
);
 
COMMENT ON COLUMN MEMBER_TBL.ID IS '아이디';
COMMENT ON COLUMN MEMBER_TBL.PW IS '패쓰워드';
COMMENT ON COLUMN MEMBER_TBL.NAME IS '이름';
COMMENT ON COLUMN MEMBER_TBL.GENDER IS '성별';
COMMENT ON COLUMN MEMBER_TBL.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER_TBL.MOBILE IS '연락처1(휴대폰)';
COMMENT ON COLUMN MEMBER_TBL.PHONE IS '연락처2(일반전화)';
COMMENT ON COLUMN MEMBER_TBL.ZIP IS '우편번호';
COMMENT ON COLUMN MEMBER_TBL.ROAD_ADDRESS IS '도로명 주소';
COMMENT ON COLUMN MEMBER_TBL.JIBUN_ADDRESS IS '지번 주소';
COMMENT ON COLUMN MEMBER_TBL.DETAIL_ADDRESS IS '상세 주소';
COMMENT ON COLUMN MEMBER_TBL.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN MEMBER_TBL.JOINDATE IS '가입일';
COMMENT ON COLUMN MEMBER_TBL.ENABLED IS '회원정보 사용 여부'; 

DROP TABLE MEMBER_TBL;

-------------------------------------------------------------

CREATE TABLE MEMBER_TBL (
ID VARCHAR(20),
PW NVARCHAR2(20),
NAME NVARCHAR2(100),
GENDER CHAR,
EMAIL NVARCHAR2(50),
MOBILE NVARCHAR2(13),
PHONE NVARCHAR2(13),
ZIP CHAR(5),
ROAD_ADDRESS NVARCHAR2(100),
JIBUN_ADDRESS NVARCHAR2(100),
DETAIL_ADDRESS NVARCHAR2(50),
BIRTHDAY DATE,
JOINDATE DATE DEFAULT CURRENT_DATE,
ENABLED NUMBER(1) DEFAULT 0
);
  
ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_TBL_ID_PK PRIMARY KEY(ID);

ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_TBL_EMAIL_U UNIQUE(EMAIL);
 
ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_TBL_MOBILE_U UNIQUE(MOBILE);
 
ALTER TABLE MEMBER_TBL
MODIFY (PW CONSTRAINT MEMBER_TBL_PW_NN NOT NULL);
 
ALTER TABLE MEMBER_TBL
MODIFY (NAME CONSTRAINT MEMBER_TBL_NAME_NN NOT NULL);
 
ALTER TABLE MEMBER_TBL
MODIFY (GENDER CONSTRAINT MEMBER_TBL_GENDER_NN NOT NULL);

ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_TBL_GENDER_CK CHECK ( GENDER IN ( 'm', 'f' ) );
 
ALTER TABLE MEMBER_TBL
MODIFY (EMAIL CONSTRAINT MEMBER_TBL_EMAIL_NN NOT NULL);
 
ALTER TABLE MEMBER_TBL
MODIFY (MOBILE CONSTRAINT MEMBER_TBL_MOBILE_NN NOT NULL);
 
ALTER TABLE MEMBER_TBL
MODIFY (PHONE  CONSTRAINT MEMBER_TBL_PHONE_NN NOT NULL);

-- 참고 제약조건(CONSTRAINT) 삭제 예시

ALTER TABLE MEMBER_TBL DROP CONSTRAINT MEMBER_TBL_EMAIL_U;

ALTER TABLE MEMBER_TBL DROP CONSTRAINT MEMBER_TBL_MOBILE_U;

ALTER TABLE MEMBER_TBL DROP CONSTRAINT MEMBER_TBL_ID_PK; 

DROP TABLE member_tbl;


-------------------------------------------------------------

/* 참고) 성별 제약조건은 아래와 같이 작성할 수도 있습니다. */
ALTER TABLE MEMBER_TBL ADD CONSTRAINT MEMBER_TBL_GENDER_CK CHECK (GENDER = 'm' OR GENDER = 'f');

--------------------------------------------------------------

-------------------------------------------------------------------------------

SELECT TO_DATE('July 8, 2024, 2:10 P.M.',
               'Month dd, YYYY, HH:MI P.M.',
               'NLS_DATE_LANGUAGE = American')
FROM DUAL;

-------------------------------------------------------------------------------

-- 비밀번호(#Abcd1234) : $2a$10$EaGQQBveqh0V3xhUFv8YEOTsk9Vxrm8idp..z9REVGcqQsJ4Ac5gu

INSERT INTO MEMBER_TBL VALUES
('abcd1111',
 '$2a$10$EaGQQBveqh0V3xhUFv8YEOTsk9Vxrm8idp..z9REVGcqQsJ4Ac5gu',
 '홍길동',
 'm',
 'abcd1111@abcd.com',
 '010-1111-3333',
 '02-1111-2222',
 '08290',
 '서울특별시 관악구 신림로 340',
 '서울특별시 관악구 신림동 1422-5 르네상스 복합쇼핑몰',
 '6층 MBC 아카데미',
 '2000-01-01',
  sysdate,
  1);
  
  
INSERT INTO MEMBER_TBL VALUES
('abcd2222',
 '$2a$10$EaGQQBveqh0V3xhUFv8YEOTsk9Vxrm8idp..z9REVGcqQsJ4Ac5gu',
 '류관순',
 'f',
 'abcd2222@efgh.com',
 '010-2222-7777',
 '02-1111-2222',
 '08290',
 '서울특별시 관악구 신림로 340',
 '서울특별시 관악구 신림동 1422-5 르네상스 복합쇼핑몰',
 '6층 MBC 컴퓨터 아카데미',
 '2000-01-01',
 TO_DATE('August 4, 2023, 2:00 P.M.',
        'Month dd, YYYY, HH:MI P.M.',
        'NLS_DATE_LANGUAGE = American'),
 1);

 UPDATE member_tbl SET
 PW='$2a$10$EaGQQBveqh0V3xhUFv8YEOTsk9Vxrm8idp..z9REVGcqQsJ4Ac5gu',
 EMAIL='java@djkangnam.com',
 ZIP='08290',
 JIBUN_ADDRESS='서울특별시 관악구 신림동 1433-120번지',
 DETAIL_ADDRESS='MBC 아카데미 신림점 별관 8층'
 WHERE ID='abcd1111';
 
 SELECT * FROM MEMBER_TBL;
 
 -- 개별 회원정보 조회
 SELECT * FROM MEMBER_TBL
 WHERE ID='abcd1111';
 
 DELETE MEMBER_TBL;
 
 DELETE MEMBER_TBL
 WHERE ID='abcd1111';
