--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-14-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "JAVA"."USER_ROLES" 
   (	"USER_ROLE_ID" NUMBER(11,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA.USER_ROLES
SET DEFINE OFF;
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (1,'mbc_1001','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (2,'mbc_1002','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (3,'mbc_1003','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (4,'mbc_1004','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (5,'mbc_1005','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (6,'mbc_1006','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (7,'mbc_1007','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (8,'mbc_1008','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (9,'mbc_1009','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (10,'mbc_1010','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (11,'mbc_1011','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (12,'mbc_1012','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (13,'mbc_1013','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (14,'mbc_1014','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (15,'mbc_1015','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (16,'mbc_1016','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (17,'mbc_1017','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (18,'mbc_1018','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (19,'mbc_1019','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (20,'mbc_1020','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (21,'mbc_1021','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (22,'mbc_1022','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (23,'mbc_1023','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (24,'mbc_1024','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (25,'mbc_1025','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (26,'mbc_1026','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (27,'mbc_1027','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (28,'mbc_1028','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (29,'mbc_1029','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (30,'mbc_1030','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (31,'mbc_1031','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (32,'mbc_1032','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (33,'mbc_1033','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (34,'mbc_1034','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (35,'mbc_1035','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (36,'mbc_1036','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (37,'mbc_1037','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (38,'mbc_1038','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (39,'mbc_1039','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (40,'mbc_1040','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (41,'mbc_1041','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (42,'mbc_1042','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (43,'mbc_1043','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (44,'mbc_1044','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (45,'mbc_1045','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (46,'mbc_1046','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (47,'mbc_1047','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (48,'mbc_1048','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (49,'mbc_1049','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (50,'mbc_1050','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (51,'mbc_1051','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (52,'mbc_1052','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (53,'mbc_1053','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (54,'mbc_1054','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (55,'mbc_1055','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (56,'mbc_1056','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (57,'mbc_1057','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (58,'mbc_1058','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (59,'mbc_1059','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (60,'mbc_1060','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (61,'mbc_1061','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (62,'mbc_1062','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (63,'mbc_1063','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (64,'mbc_1064','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (65,'mbc_1065','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (66,'mbc_1066','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (67,'mbc_1067','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (68,'mbc_1068','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (69,'mbc_1069','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (70,'mbc_1070','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (71,'mbc_1071','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (72,'mbc_1072','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (73,'mbc_1073','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (74,'mbc_1074','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (75,'mbc_1075','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (76,'mbc_1076','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (77,'mbc_1077','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (78,'mbc_1078','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (79,'mbc_1079','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (80,'mbc_1080','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (81,'mbc_1081','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (82,'mbc_1082','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (83,'mbc_1083','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (84,'mbc_1084','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (85,'mbc_1085','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (86,'mbc_1086','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (87,'mbc_1087','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (88,'mbc_1088','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (89,'mbc_1089','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (90,'mbc_1090','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (91,'mbc_1091','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (92,'mbc_1092','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (93,'mbc_1093','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (94,'mbc_1094','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (95,'mbc_1095','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (96,'mbc_1096','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (97,'mbc_1097','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (98,'mbc_1098','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (99,'mbc_1099','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (100,'mbc_1100','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (101,'abcd1111','ROLE_USER');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (110,'abcd1111','ROLE_ADMIN');
Insert into JAVA.USER_ROLES (USER_ROLE_ID,USERNAME,ROLE) values (111,'abcdjava1','ROLE_USER');
--------------------------------------------------------
--  DDL for Index SYS_C007070
--------------------------------------------------------

  CREATE UNIQUE INDEX "JAVA"."SYS_C007070" ON "JAVA"."USER_ROLES" ("USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "JAVA"."USER_ROLES" ADD PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."USER_ROLES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."USER_ROLES" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."USER_ROLES" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "JAVA"."USER_ROLES" ADD CONSTRAINT "FK_USERNAME" FOREIGN KEY ("USERNAME")
	  REFERENCES "JAVA"."MEMBER_TBL" ("ID") ENABLE;
